### ISSUE TITLE
uclust Segmentation Fault

### ISSUE THREAD

**Issue by robertzamoida** [biocore/pynast#22] opened 2022-05-20 16:30 UTC
@rcedgar
Attempting to use uclust  to run @jcmcnch MGPrimerEval repo and encounter the following problem:

System: 11th gen Intel Core i7-11850H @ 2.50 Hz, 32 GB RAM, Windows 11 Pro 21H2 64-bit, Ubuntu 20.04.4.4, Conda 4.12.0

git  clone https://github.com/<uclust location> into /MGPrimerEval/ directory
cp -a ~/MGPrimerEval/uclust/uclust/ ~/databases/
cd ./databases/
chmod a+x uclust 
./uclust = Segmentation Fault.

Any thoughts? Thanks!

**Comment by rcedgar** [comment] 2022-05-20 16:42
This seems to be an unlicensed copy of uclust, see [https://github.com/jcmcnch/MGPrimerEval/issues/3](https://github.com/jcmcnch/MGPrimerEval/issues/3).

**Comment by jcmcnch** [comment] 2022-05-20 16:49
So if I understand correctly, this is not working for @robertzamoida because the license is granted for my personal use but not his use? If so, then how do you recommend `uclust` be shared with him so he can use it as part of the pipeline to run `pyNAST`? Thanks in advance for your advice.

**Comment by rcedgar** [comment] 2022-05-20 16:52
There is no license enforcement in the binary, so I don't understand the segfault. Looks like a very standard processor and o/s, maybe checksum the binary for corruption?

**Comment by jcmcnch** [comment] 2022-05-20 17:00
Yeah I don't think the binary is corrupted since I am still able to use it fine. @robertzamoida I wonder if something here might help explain it: https://github.com/biocore/qiime/issues/1745#issuecomment-65871299

The part about `pip` and `setuptools` kind of suggests to me that this could potentially be an issue caused by `pip` though I'm not exactly clear on how. Would it be a possibility to start with a fresh Ubuntu install and try again? Or on a different linux system?

**Comment by robertzamoida** [comment] 2022-05-20 17:18
Negative. Still segmentation fault and same cksum output. Brand new install from MS Store with sudo apt update/upgrade run.

**Comment by jcmcnch** [comment] 2022-05-25 21:25
Confirmed this is related to deploying `uclust` in Windows Subsystem for Linux (WSL). @robertzamoida can you please close the issue?

**Comment by robertzamoida** [comment] 2022-05-25 22:31
Will do. First thing in the morning.

Robert Zamoida
M.S. Student: Biological and Environmental Sciences-Ecology and Ecosystem
Sciences
The Davies Lab
University of Rhode Island

**Closed as completed** 2022-05-26 15:19 UTC

**Comment by robertzamoida** [comment] 2022-05-26 15:23
Confirmed uclust works on a dual boot Windows/Linux system runnung Ubuntu 20.04.4
